name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: unit tests
      run: pwd
      run: ls
      run: python --version
      run: python -m unittest
