# This file is based on examples in
# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    # The next bit is copied from STELLOPT's github actions:
    # Note that zhucaoxiang/stellopt:latest contains stellopt but
    # zhucaoxiang/stellopt:compile does not, just the libraries it depends on.
    #container: zhucaoxiang/stellopt:latest
    container: zhucaoxiang/stellopt:test
    env:
      MACHINE: docker
      #STELLOPT_PATH: ${{ github.workspace }}/externalPackages/STELLOPT
      STELLOPT_PATH: /home/STELLOPT
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Print user and group id
      run: |
        set -ex
        id
    - name: PWD
      run: |
        set -ex
        pwd
    - name: ls -l
      run: |
        set -ex
        ls -l
    - name: ls -l /
      run: |
        set -ex
        ls -l /
    - name: ls -l /__w
      run: |
        set -ex
        ls -l /__w
    - name: ls -l /__w/mattopt
      run: |
        set -ex
        ls -l /__w/mattopt
    - name: chmod
      run: echo visitor | sudo -S chmod a+wx /__w/mattopt/mattopt
    - name: ls -l /__w/mattopt again
      run: |
        set -ex
        ls -l /__w/mattopt
    - name: ls -l /__w/mattopt/mattopt
      run: |
        set -ex
        ls -l /__w/mattopt/mattopt
    - name: ls -l /home
      run: |
        set -ex
        ls -l /home
    - name: ls -l /home/visitor
      run: |
        set -ex
        ls -l /home/visitor

    - name: env
      run: env

    #- name: Change permissions where needed
    #  run: # See https://github.com/actions/checkout/issues/211 for explanation.
    #    sudo chown -R $USER:$USER /__w
    #- name: Change permissions where needed 2
    #  run: # See https://github.com/actions/checkout/issues/211 for explanation.
    #    sudo chown -R $USER:$USER /__w/mattopt
    #- name: Change permissions where needed 3
    #  run: # See https://github.com/actions/checkout/issues/211 for explanation.
    #    sudo chown -R $USER:$USER /__w/mattopt/mattopt
    - uses: actions/checkout@v2
      #with:
      #  path: /home/visitor
      #  submodules: true
    - name: which python3 before python setup
      run: which python3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: which python3 after python setup
      run: which python3

    - name: ls -l /__t/Python/3.7.8/x64/bin
      run: ls -l /__t/Python/3.7.8/x64/bin

    - name: ls -l /__t/Python/3.7.8/x64
      run: ls -l /__t/Python/3.7.8/x64

    - name: ls -l /__t/Python/3.7.8/x64/lib
      run: ls -l /__t/Python/3.7.8/x64/lib

    - name: add python to paths
      run: |
        export LD_LIBRARY_PATH=$pythonLocation/lib
        export PATH=$pythonLocation/lib:$PATH

    - name: env after adding python
      run: env

    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install numpy scipy f90nml
    - name: Print information
      run: |
        set -ex
        env 
        pwd
        ls
        ls externalPackages
        ls externalPackages/STELLOPT
        ls /
        ls /home
        ls /home/STELLOPT
        ls /home/STELLOPT/bin
        python3 --version
    - name: Run unit tests
      run: python3 -m unittest -v
    #- name: Build LIBSTELL and VMEC
    #  run: |
    #    cd ${STELLOPT_PATH}
    #    ./build_all -o clean_debug -j 2 LIBSTELL VMEC2000